# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-TieBucketBrigade
version:      0.07
version_from: lib/Apache2/TieBucketBrigade.pm
installdirs:  site
requires:
    Apache::Test:                  
    Class::Data::Inheritable:      
    ex::override:                  
    IO::File:                      
    IO::WrapTie:                   

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
